openssl_conf = openssl_init

[openssl_init]
engines = engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
dynamic_path = /path/to/libp11/engines/libpkcs11.so
MODULE_PATH = /path/to/libnethsm_pkcs11.so
init = 0

[req]
req_extensions = custom_ext

[custom_ext]
1.2.3.4=ASN1:UTF8String:Some random data
